Dhirajsakariya/StudentMgntFE

src/Components/Sidebar/Sidebar.css
=> Dropdown Profile Changes

package-lock.json, src/Components/Login/ForgotPassword.jsx, src/Components/Login/Login.css, src/Components/Login/Login.jsx, src/Components/Login/Registration.css, src/Components/Login/Registration.jsx
Registration-Login Design, Validation
=> Registration-Login Design, Validation

src/Components/Teacher/SubjectForm.css, src/Components/Teacher/TimeTable.jsx
=> TimeTable,SubjectForm Css

src/Components/Login/Registration.css, src/Components/Login/Registration.jsx
Registration Done
Registration.css
Registration.jsx
=> Registration Done

src/Components/Login/Registration.jsx
Registration Form Field Validation
Registreation.jsx
=> Registration Form Field Validation

src/Components/Login/Login.jsx
=> Login successfully work

src/Components/Login/Registration.jsx
Registration Pasword Validation and Other Field changes
=> Registration Pasword Validation and Other Field changes

src/Components/Login/Registration.jsx
Remove Unnecessary Console from Registration.jsx
=> Remove Unnecessary Console

src/Components/Login/Registration.jsx
Registration User Exist Verification and If success then Redirect
=> Registration User Exist Verification and If success then Redirect

src/App.js, src/Components/Login/Login.css, src/Components/Login/Login.jsx, src/Components/Sidebar/AdminSidebar.jsx, src/Components/Sidebar/Sidebar.jsx, src/Components/Sidebar/StudentSidebar.jsx, src/Components/Sidebar/TeacherSidebar.jsx
=> sidebar & login page css fix

src/Components/Admin/TeacherForm.css, src/Components/Admin/TeacherForm.jsx
teacher form email exist issue solve
=> teacher form email exist issue solve

src/Components/Admin/StudentForm.jsx, src/Components/Admin/TeacherForm.css, src/Components/Admin/TeacherForm.jsx, src/Components/Login/ForgotPassword.css, src/Components/Login/ForgotPassword.jsx
=> Change in forgot-password css

src/App.js, src/Components/Admin/AdminPersonal.jsx, src/Components/Login/Login.css, src/Components/Login/Login.jsx, src/Components/Sidebar/AdminSidebar.jsx, src/Components/Sidebar/Sidebar.css, src/Components/Sidebar/StudentSidebar.jsx, src/Components/Sidebar/TeacherSidebar.jsx, src/Components/Student/StudentPersonal.jsx, src/Components/Teacher/TeacherPersonal.jsx
=> Login Success and Sidebar

src/App.js, src/Components/Admin/ParentsPortal.css, src/Components/Admin/ParentsPortal.jsx
Parents Portal
Parentsportal.jsx
Parentsportal.css
App.js
=> Parents Portal

src/Components/Login/Registration.css, src/Components/Login/Registration.jsx
Registration-Subject and standatrd get for teacher role and passing it is remaining
=> Registration subject id and standard id if teacher role

src/App.js, src/Components/Teacher/TimeTable.css, src/Components/Teacher/TimeTable.jsx
=> Timetable changes

src/Components/Sidebar/AdminSidebar.jsx, src/Components/Sidebar/StudentSidebar.jsx, src/Components/Sidebar/TeacherSidebar.jsx
=> sidebar icon

src/Components/Login/Registration.css, src/Components/Login/Registration.jsx
Registration-Standard String is split into sno and div and pass it
=> Registration-Standard String is split into sno and div and pass it

src/Components/Teacher/Standard.css, src/Components/Teacher/Standard.jsx
=> Standard css update

src/Components/Admin/TeacherForm.css, src/Components/Admin/TeacherForm.jsx
Fetch subject id and standard id in teacher form
=> Fetch subject id and standard id in teacher form

src/Components/Admin/ParentsPortal.css, src/Components/Admin/ParentsPortal.jsx, src/Components/Login/Login.jsx
LoggedInUser Stored In LocalStorage
=> LoggedInUser Stored In LocalStorage

src/Components/Admin/FeeForm.css, src/Components/Admin/FeeForm.jsx, src/Components/Student/StudentFeeForm.css, src/Components/Student/StudentFeeForm.jsx
studentfeeform and feeform css update
=> studentfeeform and feeform css update

src/App.js, src/Components/Sidebar/AdminSidebar.jsx, src/Components/Sidebar/Sidebar.css, src/Components/Sidebar/TeacherSidebar.jsx
interaction with student form and sidebar change,css
=> interaction with student form and sidebar change,css

src/Components/Admin/ParentsPortal.css, src/Components/Login/Registration.css, src/Components/Login/Registration.jsx
Registration CSS Changes 28-03-2023
=> Registration CSS 28-03-2023

src/Components/Admin/TeacherForm.css, src/Components/Admin/TeacherForm.jsx
=> Teacher Form CSS Update

src/Components/Teacher/Standard.css, src/Components/Teacher/Standard.jsx, src/Components/Teacher/TimeTable.css, src/Components/Teacher/TimeTable.jsx
=> Timetable and standard update

src/App.js, src/Components/Admin/AdminPersonal.css, src/Components/Admin/AdminPersonal.jsx, src/Components/Login/Login.jsx, src/Components/Sidebar/AdminSidebar.jsx
=> admin page personal info done

src/App.js, src/Components/Admin/AdminPersonal.css, src/Components/Admin/AdminPersonal.jsx, src/Components/Login/Login.jsx, src/Components/Sidebar/AdminSidebar.jsx, src/Components/Teacher/TimeTable.jsx
=> Timetable dropdown

src/Components/Login/Login.css
=> login css done finally

src/App.js, src/Components/Student/StudentPersonal.css, src/Components/Student/StudentPersonal.jsx
=> student personal form done

src/Components/Admin/AdminPersonal.css, src/Components/Admin/AdminPersonal.jsx, src/Components/Sidebar/AdminSidebar.jsx, src/Components/Sidebar/TeacherSidebar.jsx, src/Components/Student/StudentPersonal.css, src/Components/Student/StudentPersonal.jsx, src/Components/Teacher/TeacherPersonal.css, src/Components/Teacher/TeacherPersonal.jsx
student personal form and all css done like admin,teacher and student
=> student personal form and all css done like admin,teacher and student

src/App.js, src/Components/Sidebar/AdminSidebar.jsx, src/Components/Sidebar/Sidebar.css, src/Components/Sidebar/StudentSidebar.jsx, src/Components/Sidebar/TeacherSidebar.jsx
=> DropDown Design  Change

src/Components/Login/ForgotPassword.css, src/Components/Login/ForgotPassword.jsx, src/Components/Sidebar/AdminSidebar.jsx, src/Components/Sidebar/StudentSidebar.jsx, src/Components/Sidebar/TeacherSidebar.jsx
ForgotPassword Design and Sidebar changes
=> ForgotPassword Design and Sidebar changes

src/Components/Login/Login.css, src/Components/Login/Login.jsx
=> login css done

src/Components/Student/StudentFeeForm.css, src/Components/Student/StudentFeeForm.jsx
=> FeesConnectivity

src/Components/Admin/AdminPersonal.css, src/Components/Student/StudentPersonal.css, src/Components/Teacher/TeacherPersonal.css
css and color done personal page
=> css and color done personal page

src/Components/Admin/AdminPersonal.jsx, src/Components/Sidebar/AdminSidebar.jsx, src/Components/Sidebar/StudentSidebar.jsx, src/Components/Sidebar/TeacherSidebar.jsx, src/Components/Student/StudentPersonal.jsx, src/Components/Teacher/TeacherPersonal.jsx
=> config add link personal page

src/Components/Login/Login.jsx
login page (select role and fail login one time message done)
=> login page (select role and fail login one time message done)

src/Components/Admin/ParentsPortal.css, src/Components/Admin/ParentsPortal.jsx
=> ParentsPortal css change

src/Components/Sidebar/AdminSidebar.jsx, src/Components/Sidebar/Sidebar.css, src/Components/Sidebar/StudentSidebar.jsx, src/Components/Sidebar/TeacherSidebar.jsx
=> Sidebar.CSS Changes

src/App.js, src/Components/Admin/Search_Teacher.css, src/Components/Admin/Search_Teacher.jsx, src/Components/Admin/TeacherForm.jsx
Added Search-Teacher FIle and Teacher Details Display & Delete
=> Added Search-Teacher FIle and Teacher Details Display & Delete

src/App.js, src/Components/Admin/Search_Student.css, src/Components/Admin/Search_Student.jsx, src/Components/Admin/Search_Teacher.jsx
=> remove bootstarp

src/App.js, src/Components/Admin/Search_Student.css, src/Components/Admin/Search_Student.jsx, src/Components/Admin/Search_Teacher.css, src/Components/Admin/Search_Teacher.jsx
Bug Fix in Search Student and Teacher
=> Bug Fix in Search Student and Teacher

src/Components/Admin/Search_Student.jsx, src/Components/Admin/Search_Teacher.jsx
Bug fix of Table in Search Student & Teacher
=> Bug fix of Table in Search Student & Teacher

src/Components/Admin/AdminPersonal.css, src/Components/Sidebar/AdminSidebar.jsx, src/Components/Student/StudentPersonal.css, src/Components/Teacher/TeacherPersonal.css
sidbar add path and personal page css fix
=> sidbar add path and personal page css fix

src/Components/Admin/AdminPersonal.css, src/Components/Student/StudentPersonal.css, src/Components/Teacher/TeacherPersonal.css
=> personal css finalyy done

src/Components/Student/StudentFeeForm.css, src/Components/Student/StudentFeeForm.jsx
=> change css studentfeeform

src/Components/Admin/Search_Student.css, src/Components/Admin/Search_Student.jsx, src/Components/Admin/StudentForm.css, src/Components/Admin/StudentForm.jsx
bug fixed & css change in StudentForm
=> bug fixed & css change in StudentForm

src/Components/Teacher/TimeTable.jsx
=> Timetable post data

src/Components/Admin/StudentForm.jsx, src/Components/Teacher/TimeTable.jsx
=> Timetable Success

src/Components/Admin/FeeForm.css, src/Components/Admin/FeeForm.jsx, src/Components/Student/StudentFeeForm.css, src/Components/Student/StudentFeeForm.jsx
change css_set msg fees already paid
=> change css_set msg fees already paid

src/App.js, src/Components/Login/Logout.jsx, src/Components/Sidebar/AdminSidebar.jsx, src/Components/Sidebar/StudentSidebar.jsx, src/Components/Sidebar/TeacherSidebar.jsx
=> sidbar add logout

src/App.js, src/Components/Admin/StudentMarks.css, src/Components/Admin/StudentMarks.jsx, src/Components/Sidebar/AdminSidebar.jsx
=> Add student marks Form

src/App.js, src/Components/Sidebar/AdminSidebar.jsx
=> Bug fixed in app.js

src/Components/Admin/Search_Student.jsx, src/Components/Admin/Search_Teacher.css, src/Components/Admin/Search_Teacher.jsx, src/Components/Admin/TeacherForm.jsx, src/Components/Sidebar/AdminSidebar.jsx
=> View Teacher Details On Popup 

src/Components/Admin/Search_Student.css, src/Components/Admin/Search_Student.jsx
view details on popup and search student  in SearchStudent
=> view details on popup and search student in SearchStudent

src/Components/Admin/Search_Teacher.css, src/Components/Admin/Search_Teacher.jsx
=> Add SearchQuery

src/Components/Admin/AdminPersonal.jsx, src/Components/Sidebar/AdminSidebar.jsx, src/Components/Sidebar/StudentSidebar.jsx, src/Components/Sidebar/TeacherSidebar.jsx, src/Components/Teacher/TeacherPersonal.jsx
=> Bug Fixed in Sidebar

src/App.js, src/Components/Admin/AdminPersonal.jsx, src/Components/Admin/ParentsPortal.jsx, src/Components/Admin/Search_Student.jsx, src/Components/Admin/Search_Teacher.jsx, src/Components/Admin/StudentForm.jsx, src/Components/Admin/StudentMarks.jsx, src/Components/Admin/TeacherForm.jsx, src/Components/Login/PageNotFound.jsx, src/Components/Sidebar/AdminSidebar.jsx, src/Components/Sidebar/StudentSidebar.jsx, src/Components/Sidebar/TeacherSidebar.jsx, src/Components/Student/Student.jsx, src/Components/Student/StudentFeeForm.jsx, src/Components/Student/StudentPersonal.jsx, src/Components/Teacher/Standard.jsx, src/Components/Teacher/Student_Form.jsx, src/Components/Teacher/TeacherPersonal.jsx, src/Components/Teacher/TimeTable.jsx
User not moving another user authentication and page not found create page
=> User not moving another user authentication and page not found create page

src/Components/Teacher/TimeTable.jsx
=> Timetable Complete

src/Components/Admin/AdminPersonal.jsx, src/Components/Admin/ParentsPortal.jsx, src/Components/Admin/Search_Student.jsx, src/Components/Admin/Search_Teacher.jsx, src/Components/Admin/StudentForm.jsx, src/Components/Admin/StudentMarks.jsx, src/Components/Admin/TeacherForm.jsx, src/Components/Login/Login.jsx, src/Components/Sidebar/AdminSidebar.jsx, src/Components/Sidebar/StudentSidebar.jsx, src/Components/Sidebar/TeacherSidebar.jsx, src/Components/Student/Student.jsx, src/Components/Student/StudentFeeForm.jsx, src/Components/Student/StudentPersonal.jsx, src/Components/Teacher/Standard.jsx, src/Components/Teacher/Student_Form.jsx, src/Components/Teacher/TeacherPersonal.jsx, src/Components/Teacher/TimeTable.jsx
all page not redirect without role
=> all page not redirect without role

package-lock.json, package.json
=> Add Student Marks table

src/App.js, src/Components/Teacher/AddExamSchedule.css, src/Components/Teacher/AddExamSchedule.jsx
=> Add-Student-Marks-table

src/Components/Admin/Search_Student.css, src/Components/Admin/Search_Student.jsx
=> Bug fixed search_student

package.json, src/Components/Admin/Search_Teacher.css, src/Components/Admin/Search_Teacher.jsx
=> Complete Search_Teacher Form

src/Components/Admin/Search_Student.css, src/Components/Admin/Search_Student.jsx
=> complete search student form

src/App.js, src/Components/Admin/Search_Student.css, src/Components/Login/ForgotPassword.jsx, src/Components/Login/Login.jsx, src/Components/Login/Logout.jsx, src/Components/Login/PageNotFound.jsx, src/Components/Login/PrivateRoute.jsx, src/Components/Login/Registration.jsx, src/Components/Sidebar/AdminSidebar.jsx, src/Components/Sidebar/StudentSidebar.jsx, src/Components/Sidebar/TeacherSidebar.jsx, src/Components/Teacher/AddExamSchedule.jsx
add / to /login and janvi shraddha changes
=> add / to /login and janvi shraddha changes

src/Components/Admin/AdminPersonal.jsx, src/Components/Admin/ParentsPortal.jsx, src/Components/Admin/Search_Student.jsx, src/Components/Admin/Search_Teacher.jsx, src/Components/Admin/StudentForm.jsx, src/Components/Admin/StudentMarks.jsx, src/Components/Admin/TeacherForm.jsx, src/Components/Sidebar/AdminSidebar.jsx, src/Components/Sidebar/StudentSidebar.jsx, src/Components/Sidebar/TeacherSidebar.jsx, src/Components/Student/Student.jsx, src/Components/Student/StudentFeeForm.jsx, src/Components/Student/StudentPersonal.jsx, src/Components/Teacher/Standard.jsx, src/Components/Teacher/Student_Form.jsx, src/Components/Teacher/TeacherPersonal.jsx, src/Components/Teacher/TimeTable.jsx
=> all chandges console file

src/Components/Sidebar/TeacherSidebar.jsx
add exam schedule in teacher sidebar
=> add exam schedule in teacher sidebar

src/Components/Student/StudentFeeForm.css, src/Components/Student/StudentFeeForm.jsx
=> addRemainingAmount

src/Components/Student/StudentFeeForm.css, src/Components/Student/StudentFeeForm.jsx
=> Fee Form css change

src/Components/Admin/AdminPersonal.jsx, src/Components/Admin/Search_Student.css, src/Components/Admin/Search_Student.jsx, src/Components/Admin/StudentForm.css, src/Components/Admin/StudentForm.jsx, src/Components/Student/StudentPersonal.jsx, src/Components/Teacher/TeacherPersonal.jsx
add buttons for student & family in search student
=> add buttons for student & family in search student

src/Components/Admin/Search_Teacher.css, src/Components/Admin/Search_Teacher.jsx, src/Components/Admin/TeacherForm.css, src/Components/Admin/TeacherForm.jsx, src/Components/Sidebar/AdminSidebar.jsx
Add Teacher Button in Search Teacher Form
=> Add Teacher Button in Search Teacher Form

src/Components/Admin/ParentsPortal.jsx
delete working finally familymember
=>  delete working finally familymember

src/Components/Teacher/AddExamSchedule.jsx
Add-Exam-Schedule delete is working
=> Add-Exam-Schedule delete is working

src/Components/Teacher/TimeTable.jsx
=> Timetable Reset Form

src/Components/Admin/Search_Student.css, src/Components/Admin/Search_Student.jsx
Add StudentMark button added in search student
=> Add StudentMark button added in search student

src/Components/Admin/AdminPersonal.css, src/Components/Admin/ParentsPortal.css, src/Components/Admin/Search_Student.css, src/Components/Admin/Search_Student.jsx, src/Components/Admin/Search_Teacher.css, src/Components/Admin/Search_Teacher.jsx, src/Components/Admin/StudentForm.css, src/Components/Admin/StudentMarks.css, src/Components/Admin/TeacherForm.css, src/Components/Login/ForgotPassword.css, src/Components/Login/Login.css, src/Components/Login/Registration.css, src/Components/Sidebar/Sidebar.css, src/Components/Student/Student.css, src/Components/Student/StudentFeeForm.css, src/Components/Student/StudentPersonal.css, src/Components/Teacher/AddExamSchedule.css, src/Components/Teacher/Standard.css, src/Components/Teacher/Student_Form.css, src/Components/Teacher/TeacherPersonal.css, src/Components/Teacher/TimeTable.css, src/index.css
=> Design of All Site

src/Components/Teacher/AddExamSchedule.jsx
Add Standard & Subject (Error Solution Done) in AddExamSchedule Form
=> Add Standard & Subject (Error Solution Done) in AddExamSchedule Form

src/Components/Admin/Search_Student.jsx, src/Components/Admin/StudentForm.jsx
Store StudentId in Search Student for add Family and Student Marks
=> Store StudentId in Search Student for add Family and Student Marks

src/Components/Admin/Search_Student.css
=> css updated in search student

src/Components/Admin/AdminPersonal.css, src/Components/Admin/ParentsPortal.css, src/Components/Admin/Search_Student.css, src/Components/Admin/Search_Student.jsx, src/Components/Admin/Search_Teacher.css, src/Components/Admin/StudentForm.css, src/Components/Admin/StudentMarks.css, src/Components/Admin/StudentMarks.jsx, src/Components/Admin/TeacherForm.css, src/Components/Login/ForgotPassword.css, src/Components/Login/Login.css, src/Components/Login/Registration.css, src/Components/Student/StudentFeeForm.css, src/Components/Student/StudentFeeForm.jsx, src/Components/Student/StudentPersonal.css, src/Components/Teacher/Student_Form.css, src/Components/Teacher/TeacherPersonal.css, src/Components/Teacher/TimeTable.css
=> All inputbox css change

src/Components/Admin/StudentMarks.css, src/Components/Admin/StudentMarks.jsx
=> fetch_name_subjects

src/Components/Teacher/AddExamSchedule.css, src/Components/Teacher/AddExamSchedule.jsx
=> Update schedule standard wise

src/Components/Admin/ParentsPortal.jsx
parents portal set condition only one parents select
=> parents portal set condition only one parents select

src/Components/Admin/Search_Student.css, src/Components/Admin/Search_Teacher.css, src/Components/Admin/Search_Teacher.jsx
=> popup close button css

src/Components/Admin/StudentMarks.css, src/Components/Admin/StudentMarks.jsx
=> change css based on id

package.json, src/Components/Login/Registration.css, src/Components/Login/Registration.jsx
Admin registration bug fix
Registration.css - Changes based on id instead of className
=> Admin registration bug fix

src/Components/Student/Parents.jsx
=> Get Parents in Student

src/Components/Admin/ParentsPortal.css, src/Components/Admin/ParentsPortal.jsx
Get Post Edit Delete Done in Parents Portal
=> Get Post Edit Delete Done

src/App.js, src/Components/Admin/StudentForm.jsx, src/Components/Student/TimeTableViewer.css, src/Components/Student/TimeTableViewer.jsx, src/Components/Teacher/TimeTable.css, src/Components/Teacher/TimeTable.jsx
=> Student Sidebar Add Timetable

src/Components/Admin/Search_Student.css, src/Components/Admin/Search_Student.jsx, src/Components/Admin/Search_Teacher.css, src/Components/Admin/Search_Teacher.jsx
Add heading in search teacher & student
=> Add heading in search teacher & student

src/Components/Admin/Search_Student.jsx
popup gender value solved in seach student
=> popup gender value solved in seach student

src/Components/Admin/TeacherForm.css, src/Components/Sidebar/StudentSidebar.jsx
StudentSidebar Add Path TimeTable
=> StudentSidebar Add Path TimeTable

src/Components/Student/TimeTableViewer.css, src/Components/Student/TimeTableViewer.jsx
StudentSidebar TimeTable CSS Changes
=> StudentSidebar TimeTable CSS Changes

src/App.js, src/Components/Sidebar/TeacherSidebar.jsx, src/Components/Teacher/StudentReport.jsx
Add StudentReport TeacherSidebar
=> Add StudentReport TeacherSidebar

src/Components/Student/Parents.jsx
Fetched Parents Details on Student SideBar
=> Fetched Parents Details on Student SideBar

src/App.js, src/Components/Admin/Search_Student.css, src/Components/Admin/Search_Teacher.css, src/Components/Admin/StudentForm.css, src/Components/Admin/TeacherForm.css
AdminSide Button Hover CSS Added
=> AdminSide Button Hover CSS Added

src/Components/Teacher/TimeTable.jsx
=> Add TimeTableForm

src/Components/Student/Parents.css, src/Components/Student/Parents.jsx
add css to the parents from in student side
=> add css to the parents from in student side

src/Components/Admin/ParentsPortal.jsx
parents portal edit in adminside
=> parents portal edit in adminside

src/Components/Admin/StudentMarks.css, src/Components/Admin/StudentMarks.jsx, src/Components/Student/StudentFeeForm.css, src/Components/Student/StudentFeeForm.jsx, src/Components/Student/StudentPersonal.css
=> edit_delete_studentmarks

src/Components/Admin/ParentsPortal.jsx
=> card show family details

src/Components/Admin/ParentsPortal.jsx
without refferesh button show cards
=> without refferesh button show cards

src/Components/Teacher/TimeTable.css, src/Components/Teacher/TimeTable.jsx
Timetable Update UI in Teacher
=> Timetable Update UI in Teacher

src/Components/Admin/Search_Student.css, src/Components/Admin/Search_Teacher.css, src/Components/Admin/StudentForm.css, src/Components/Admin/TeacherForm.css
=> Button CSS Add Cursor Pointer

src/Components/Admin/ParentsPortal.jsx
=> Bug Fixed in ParentsPortal

src/Components/Admin/ParentsPortal.css, src/Components/Admin/ParentsPortal.jsx
Parents Poratal successfully done
=> Parents Poratal Done

src/Components/Admin/ParentsPortal.css, src/Components/Admin/ParentsPortal.jsx, src/Components/Admin/StudentForm.css, src/Components/Admin/StudentForm.jsx, src/Components/Admin/TeacherForm.css, src/Components/Admin/TeacherForm.jsx, src/Components/Login/Registration.jsx
CSS Change for Country Dropdown and Gender
=> CSS Change for Country Dropdown and Gender

src/Components/Admin/ParentsPortal.css, src/Components/Admin/ParentsPortal.jsx
=> parents portal completed

src/Components/Teacher/StudentReport.css, src/Components/Teacher/StudentReport.jsx
=> studenr report page

src/Components/Teacher/StudentReport.css, src/Components/Teacher/StudentReport.jsx
=> StudentReport Form css Change

src/Components/Login/ForgotPassword.css, src/Components/Login/ForgotPassword.jsx, src/Components/Login/Login.css, src/Components/Login/Login.jsx, src/Components/Login/Registration.jsx
Footer Add to Other Pages and also change css
=> Footer Add to Other Pages and also change css

src/Components/Admin/Search_Teacher.css, src/Components/Student/StudentPersonal.css, src/Components/Student/StudentPersonal.jsx
StudentPersonal Form css Change
=> StudentPersonal Form css Change

src/Components/Admin/Search_Student.css, src/Components/Admin/Search_Student.jsx
=> Updated Search Student form

public/index.html, src/Components/Admin/Search_Student.css, src/Components/Admin/Search_Student.jsx, src/Components/Admin/StudentForm.jsx, src/Components/Admin/StudentMarks.jsx, src/Components/Sidebar/TeacherSidebar.jsx
Search Student Added In TeacherSidebar
=> Search Student Added In TeacherSidebar

src/Components/Teacher/TimeTable.css, src/Components/Teacher/TimeTable.jsx
=> Final-TimeTable

src/Components/Student/Parents.jsx
Update Parents Page on Student Side
=> Update Parents Page on Student Side

src/Components/Teacher/AddExamSchedule.css, src/Components/Teacher/AddExamSchedule.jsx
exam schedule toast and exam type standard set
=> exam schedule toast and exam type standard set

src/Components/Teacher/AddExamSchedule.jsx
Added ExamSchedule in AdminSide
=> Added ExamSchedule in AdminSide

src/Components/Dashboard/Navigationbar.css, src/Components/Dashboard/Navigationbar.jsx, src/Components/Sidebar/TeacherSidebar.jsx, src/Components/Teacher/Standard.css, src/Components/Teacher/StudentReport.css, src/Components/Teacher/TeacherPersonal.css
navigatebar and teacher side css change
=> navigatebar and teacher side css change

src/Components/Teacher/TimeTable.jsx
=> Subject Fetch By StandardId

src/Components/Admin/Search_Student.css, src/Components/Admin/Search_Student.jsx, src/Components/Sidebar/StudentSidebar.jsx, src/Components/Student/StudentPersonal.css
Update Student Detail popup of search student
=> Update Student Detail popup of search student 

src/Components/Admin/Search_Teacher.jsx, src/Components/Teacher/StudentReport.css
student form and search teacher form css change
=> student form and search teacher form css change

src/Components/Sidebar/AdminSidebar.jsx, src/Components/Sidebar/StudentSidebar.jsx, src/Components/Sidebar/TeacherSidebar.jsx
Logout Path Changing From Login To Home At Sidebars
=> Logout Path Changing From Login To Home At Sidebars

src/Components/Dashboard/Navigationbar.css, src/Components/Dashboard/Navigationbar.jsx
active class remove in navigationbar form
=> active class remove in navigationbar form

src/Components/Admin/ParentsPortal.jsx, src/Components/Admin/TeacherForm.css, src/Components/Admin/TeacherForm.jsx, src/Components/Teacher/StudentReport.jsx
StudentReport and ParentsPortal Added Both(admin,Teacher) Side
=> StudentReport and ParentsPortal Added Both(admin,Teacher) Side

src/Components/Admin/ParentsPortal.jsx
parents portal bug on mobile number fixed
=> bug on mobile number fixed

src/Components/Teacher/AddExamSchedule.jsx
=> Dropdown Bug-Fix

src/Components/Admin/Search_Student.css, src/Components/Admin/Search_Student.jsx
add parent_portal  button in Search student form in adminside
=> add parent_portal  button in Search student form in adminside

src/Components/Teacher/AddExamSchedule.jsx, src/Components/Teacher/TimeTable.jsx
=> Add Edit Code in ExamSchedule

src/App.js, src/Components/Student/Exam_Schedule.css, src/Components/Student/Exam_Schedule.jsx
add exam schedule form in studentside
=> add exam schedule form in studentside 

src/App.js, src/Components/Admin/FeesCalculators.jsx, src/Components/Admin/Search_Student.css, src/Components/Admin/Search_Student.jsx
=> admin side fees

src/Components/Student/Exam_Schedule.css, src/Components/Student/Exam_Schedule.jsx
complete exam Schedule on student side
=> complete exam Schedule on student side

src/Components/Student/Exam_Schedule.jsx
set data on date acending order in exam schedule
=> set data on date acending order in exam schedule

src/Components/Student/TimeTableViewer.css, src/Components/Student/TimeTableViewer.jsx
=> Fetch Timetable Student Side

src/Components/Student/TimeTableViewer.css, src/Components/Student/TimeTableViewer.jsx
css apply to the timetable student side
=> css apply to the timetable student side

src/Components/Admin/FeesCalculators.css, src/Components/Admin/FeesCalculators.jsx
admin side fees done  with popup functionallyty
=> admin side fees done  with popup functionallyty

src/Components/Admin/Search_Student.css
heading css update in search student
=> heading css update in search student

src/Components/Admin/FeesCalculators.css, src/Components/Admin/FeesCalculators.jsx
print done function to fees reciepts with css
=> print done function to fees reciepts with css

src/Components/Admin/FeesCalculators.css, src/Components/Admin/FeesCalculators.jsx
messaege show frequency only one time adjust the width
=> messaege show frequency only one time adjust the width

src/Components/Admin/FeesCalculators.css
=> color chagne simple and hover

src/Components/Admin/StudentForm.css, src/Components/Admin/StudentForm.jsx
=> Add student photo admin side

src/Components/Admin/StudentForm.css, src/Components/Admin/StudentForm.jsx, src/Components/Student/TimeTableViewer.css, src/Components/Teacher/TimeTable.css
Timetable color change & TeacherSide Upload Photo
=> Timetable color change & TeacherSide Upload Photo

src/Components/Student/StudentFeeForm.css, src/Components/Student/StudentFeeForm.jsx
student side fees show with css done
=> student side fees show with css done

src/Components/Student/StudentFeeForm.jsx
onclick method in submit the form student side
=> onclick method in submit the form student side

src/Components/Admin/FeesCalculators.css, src/Components/Student/StudentFeeForm.css
css change f12 open then form cut solve this error
=> css change f12 open then form cut solve this error

src/Components/Admin/Search_Student.css, src/Components/Admin/Search_Student.jsx
paging search teacher finaaly done with css
=> paging search teacher finaaly done with css

src/Components/Admin/Search_Student.css, src/Components/Admin/Search_Student.jsx
remove the icone and add how many page that number
=> remove the icone and add how many page that number

src/Components/Admin/Search_Student.jsx
change teacher side gender icone****
=> change teacher side gender icone

src/Components/Sidebar/StudentSidebar.jsx, src/Components/Student/Exam_Schedule.css, src/Components/Student/Exam_Schedule.jsx, src/Components/Student/TimeTableViewer.css, src/Components/Student/TimeTableViewer.jsx, src/Components/Teacher/TimeTable.css, src/Components/Teacher/TimeTable.jsx
CSS Change in TimeTable and StudentSide ExamSchedule
=> CSS Change in TimeTable and StudentSide ExamSchedule

src/Components/Teacher/AddExamSchedule.css, src/Components/Teacher/AddExamSchedule.jsx
=> edit complete

src/Components/Teacher/Standard.css, src/Components/Teacher/Standard.jsx
=> dark them add standard done

src/Components/Teacher/AddExamSchedule.jsx
=> Done-Add-Exam-Schedule

src/Components/Admin/StudentMarks.css, src/Components/Admin/StudentMarks.jsx
=> bug solve in student mark.css

src/App.js, src/Components/Sidebar/StudentSidebar.jsx, src/Components/Student/IDCard.css, src/Components/Student/IDCard.jsx
=> i card with qr code

src/Components/Student/IDCard.css, src/Components/Student/IDCard.jsx
css and some king of the logic change
=> css and some king of the logic change

src/Components/Student/IDCard.css, src/Components/Student/IDCard.jsx
=> idcard file design change

src/Components/Admin/Search_Student.css, src/Components/Admin/Search_Student.jsx, src/Components/Student/IDCard.jsx
proper add family i search student and id card add family api call
=> proper add family i search student and id card add family api call

src/Components/Student/IDCard.css, src/Components/Student/IDCard.jsx
=> idcard form design change

src/Components/Admin/FeesCalculators.css, src/Components/Admin/FeesCalculators.jsx, src/Components/Student/IDCard.jsx
Fess  form css change and parents detailes add in qr code
=> Fess  form css change and parents detailes add in qr code
